package com.miaosha.dateobject;

public class SequenceDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_values
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    private Integer currentValues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_values
     *
     * @return the value of sequence_info.current_values
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public Integer getCurrentValues() {
        return currentValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_values
     *
     * @param currentValues the value for sequence_info.current_values
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public void setCurrentValues(Integer currentValues) {
        this.currentValues = currentValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Wed Feb 06 22:58:06 CST 2019
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}