package com.miaosha.dao;

import com.miaosha.dateobject.ItemDo;

import java.util.List;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    ItemDo selectByPrimaryKey(Integer id);

    List<ItemDo> selectList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 21:34:49 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);

    void increaseSales(Integer id,Integer amount);
}