package com.miaosha.dao;

import com.miaosha.dateobject.OrderDo;

public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 03 12:25:31 CST 2019
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 03 12:25:31 CST 2019
     */
    int insertSelective(OrderDo record);
}